// 36 product seed data for REIKS catalog
import type { Product } from './types'

export const SEED_PRODUCTS: Omit<Product, 'id' | 'created_at' | 'views'>[] = [
    // ─── RINGS ───
    {
        name: "Classic 22K Mirror Band",
        slug: "classic-22k-band",
        category: "rings",
        metal: "gold",
        default_karat: 22,
        available_karats: [14, 18, 22],
        base_weight_grams: 6,
        making_charges_per_gram: 450,
        images: ["/images/Gemini_Generated_Image_lcdd1klcdd1klcdd.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A timeless masterpiece of purity. This substantial 22K yellow gold band features a mirror-polished finish and a comfort-fit interior, designed for those who value understated luxury and investment-grade gold.",
        short_description: "Timeless 22K gold mirror-finish band",
        tags: ["classic", "bridal", "unisex", "investment"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 1,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "6 grams (estimated)" },
            { label: "Hallmark", value: "BIS 916 (Chennai)" },
            { label: "Finish", value: "High-Polish Mirror" },
            { label: "Style", value: "Pure Gold Essentials" }
        ]
    },
    {
        name: "Chennai Figural Signet Ring",
        slug: "signet-ring",
        category: "rings",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 28,
        making_charges_per_gram: 550,
        images: ["/images/Gemini_Generated_Image_xp4ffxp4ffxp4ffx.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A dense 22K yellow gold signet ring featuring a complex micro-embossed sculpture of a standing deity. A symbol of legacy and authority, crafted with Chennai's finest temple jewelry techniques.",
        short_description: "Heritage figural signet in solid 22K gold",
        tags: ["statement", "men", "heritage", "temple"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 2,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "28 grams (estimated)" },
            { label: "Hallmark", value: "BIS 916 (Chennai)" },
            { label: "Detailing", value: "Hand-embossed Micro-sculpture" },
            { label: "Style", value: "Chennai Temple Collection" }
        ]
    },
    {
        name: "Scottish Thistle Signet Ring",
        slug: "minimalist-18k-ring",
        category: "rings",
        metal: "gold",
        default_karat: 22,
        available_karats: [14, 18, 22],
        base_weight_grams: 19,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_w3dbxtw3dbxtw3db.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A detailed 22K yellow gold signet ring featuring a micro-engraved traditional Scottish Thistle crest. A perfect blend of Celtic heritage and modern luxury craftsmanship.",
        short_description: "Micro-engraved Scottish Thistle crest ring",
        tags: ["heritage", "men", "celtic", "bespoke"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 3,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "19 grams (estimated)" },
            { label: "Hallmark", value: "BIS 916" },
            { label: "Engraving", value: "Micro-sculpted Highland Thistle" },
            { label: "Style", value: "Heritage Gentleman's Series" }
        ]
    },
    {
        name: "Articulated Pavé Stacking Set",
        slug: "stacking-rings-set",
        category: "rings",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18],
        base_weight_grams: 8,
        making_charges_per_gram: 400,
        images: ["/images/Gemini_Generated_Image_57djwd57djwd57dj.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A trilogy of 18K white gold bands featuring an intricate filigree lace pattern completely encrusted with high-clarity pavé diamonds. Designed to be worn as a statement set or layered with heirloom pieces.",
        short_description: "Diamond-encrusted filigree stacking set",
        tags: ["diamond", "women", "couture", "stackable"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 4,
        specifications: [
            { label: "Metal", value: "18K Solid White Gold" },
            { label: "Diamonds", value: "1.20 total carat weight (F-G color, VVS clarity)" },
            { label: "Gold Weight", value: "8 grams (estimated)" },
            { label: "Texture", value: "Filigree Lace Pattern" },
            { label: "Style", value: "Contemporary Couture" }
        ]
    },
    {
        name: "Phoenix Rising Signet",
        slug: "twisted_rope_ring",
        category: "rings",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 25,
        making_charges_per_gram: 600,
        images: ["/images/Gemini_Generated_Image_vbpsqkvbpsqkvbps.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A substantial 22K yellow gold signet ring with a highly detailed, embossed micro-sculpture of a Phoenix rising from the flames. Symbolizing rebirth and eternal strength.",
        short_description: "Hand-braided Phoenix motif in solid 22K gold",
        tags: ["mythological", "men", "handmade", "artisan"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 5,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "25 grams (estimated)" },
            { label: "Detailing", value: "Embossed Phoenix Micro-sculpture" },
            { label: "Hallmark", value: "BIS 916" },
            { label: "Style", value: "Mythological Heritage Collection" }
        ]
    },
    {
        name: "Lion Rampant Legacy Ring",
        slug: "dome-cocktail-ring",
        category: "rings",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 22,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_w94bk3w94bk3w94b.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A robust 22K yellow gold signet ring featuring a finely micro-engraved Scottish Lion Rampant crest. This sculptural piece commands attention and represents a legacy of authority.",
        short_description: "Scottish Lion Rampant signet in 22K gold",
        tags: ["statement", "heraldry", "men", "luxury"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 6,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "22 grams (estimated)" },
            { label: "CREST", value: "Micro-engraved Lion Rampant" },
            { label: "Hallmark", value: "BIS 916" },
            { label: "Style", value: "Heraldic Heritage Series" }
        ]
    },

    // ─── CHAINS ───
    {
        name: "Solid Gold Cuban Link 20\"",
        slug: "cuban-link-20",
        category: "chains",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 85,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_k4xtffk4xtffk4xt.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "The definitive urban classic. Hand-assembled 22K gold links with a high-glow finish and a custom-engineered safety clasp. Shown here in a substantial 20-inch length for maximum impact.",
        short_description: "Classic hand-linked Cuban chain (85g)",
        tags: ["classic", "men", "statement", "urban"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 7,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "85 grams (estimated)" },
            { label: "Chain Length", value: "20 inches" },
            { label: "Thickness", value: "7.5mm" },
            { label: "Clasp", value: "Reinforced Large Lobster" },
            { label: "Hallmark", value: "BIS 916" }
        ]
    },
    {
        name: "Investment Cuban Necklace 24\"",
        slug: "cuban-link-24",
        category: "chains",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 110,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_8zyzdu8zyzdu8zyz.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A classic, dense, solid 22K yellow gold Cuban link necklace with polished interlocking links. At 24 inches, this monumental piece offers unmatched presence and significant gold investment value.",
        short_description: "Heavyweight 24\" investment chain (110g)",
        tags: ["statement", "men", "heavy", "investment"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 8,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "110 grams (estimated)" },
            { label: "Chain Length", value: "24 inches" },
            { label: "Thickness", value: "8.5mm" },
            { label: "Clasp", value: "Reinforced Security Lobster" },
            { label: "Hallmark", value: "BIS 916" }
        ]
    },
    {
        name: "Liquid Shine Box Chain 18\"",
        slug: "box-chain-18",
        category: "chains",
        metal: "gold",
        default_karat: 22,
        available_karats: [14, 18, 22],
        base_weight_grams: 35,
        making_charges_per_gram: 450,
        images: ["/images/Gemini_Generated_Image_vdxpe6vdxpe6vdxp.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Geometric precision meets fluid movement. Sharp square links in solid gold create a shimmering 'liquid' effect on the neckline. Perfect for the most significant pendants.",
        short_description: "Liquid-shine golden box chain (35g)",
        tags: ["versatile", "men", "women", "pendant-ready"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 9,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "35 grams (estimated)" },
            { label: "Chain Length", value: "18 inches" },
            { label: "Clasp", value: "Integrated Box Clasp" },
            { label: "Hallmark", value: "BIS 916" },
            { label: "Style", value: "Sleek Professional" }
        ]
    },
    {
        name: "Diamond-Cut Rope Chain 22\"",
        slug: "rope-chain-22",
        category: "chains",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 65,
        making_charges_per_gram: 550,
        images: ["/images/Gemini_Generated_Image_xp4ffxp4ffxp4ffx_1.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A cascade of twisted light. This diamond-cut rope chain maximizes surface area to sparkle brilliantly with every movement. A thick and robust choice for a commanding presence.",
        short_description: "Diamond-cut twisted rope chain (65g)",
        tags: ["classic", "men", "textured", "sparkle"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 10,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "65 grams (estimated)" },
            { label: "Chain Length", value: "22 inches" },
            { label: "Detailing", value: "Diamond-Cut Twisted Links" },
            { label: "Clasp", value: "Large Lobster" },
            { label: "Hallmark", value: "BIS 916" }
        ]
    },
    {
        name: "Refined Italian Figaro 20\"",
        slug: "figaro-chain-20",
        category: "chains",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18, 22],
        base_weight_grams: 55,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_w94bk3w94bk3w94b.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Italian sophistication redefined. Featuring a rhythmic link pattern, this 20-inch Figaro chain is a masterpiece of European jewelry design, presented in a substantial weight for the discerning collector.",
        short_description: "Refined Italian pattern Figaro chain (55g)",
        tags: ["italian", "men", "classic", "style"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 11,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Gold Weight", value: "55 grams (estimated)" },
            { label: "Chain Length", value: "20 inches" },
            { label: "Clasp", value: "Security Lobster" },
            { label: "Hallmark", value: "18K / 750 (UK)" }
        ]
    },
    {
        name: "Solid Gold Wheat Chain 18\"",
        slug: "wheat-chain-18",
        category: "chains",
        metal: "gold",
        default_karat: 18,
        available_karats: [18, 22],
        base_weight_grams: 45,
        making_charges_per_gram: 600,
        images: ["/images/Gemini_Generated_Image_2xuh5w2xuh5w2xuh.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A magnificent solid 18K yellow gold Wheat chain, shown at 18 inches. Featuring an intricate Espiga weave providing exceptional strength and a silk-like feel.",
        short_description: "Durable silk-feel wheat chain (45g)",
        tags: ["delicate", "women", "artisan", "strength"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 12,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Gold Weight", value: "45 grams (estimated)" },
            { label: "Chain Length", value: "18 inches" },
            { label: "Thickness", value: "4.5mm" },
            { label: "Clasp", value: "Detached Lobster (Engraved)" },
            { label: "Hallmark", value: "18K / 750 (UK Hallmark)" }
        ]
    },

    // ─── PENDANTS ───
    {
        name: "Sacred Om Filigree Pendant",
        slug: "om-pendant",
        category: "pendants",
        metal: "gold",
        default_karat: 18,
        available_karats: [18, 22],
        base_weight_grams: 12,
        making_charges_per_gram: 700,
        images: ["/images/Gemini_Generated_Image_k311qyk311qyk311.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A round 18K yellow gold pendant featuring a prominent, detailed Devanagari Om symbol (ॐ). With a granulated border and accent pavé diamonds embedded within the sacred curves, this piece is a masterpiece of spiritual devotion.",
        short_description: "Sacred 18K gold Om with diamond accents",
        tags: ["spiritual", "men", "women", "devotion"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 13,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Stones", value: "Accent Pavé Diamonds (0.25 ctw)" },
            { label: "Gold Weight", value: "12 grams (estimated)" },
            { label: "Dimensions", value: "Diameter: 32mm" },
            { label: "Style", value: "Spiritual Heritage Collection" }
        ]
    },
    {
        name: "Lord Ganesha Filigree Pendant",
        slug: "ganesh-pendant",
        category: "pendants",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18, 22],
        base_weight_grams: 14,
        making_charges_per_gram: 750,
        images: ["/images/Gemini_Generated_Image_g9txjmg9txjmg9tx.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A detailed 18K yellow gold pendant featuring a finely embossed relief of seated Lord Ganesha with attributes. Framed by an ornate granulated border, it represents wisdom and new beginnings.",
        short_description: "Embossed 18K Ganesha pendant with ruby accents",
        tags: ["religious", "heritage", "unisex"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 14,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Stones", value: "Kundan-style Ruby accents (0.35 ctw)" },
            { label: "Gold Weight", value: "14 grams (estimated)" },
            { label: "Dimensions", value: "Diameter: 35mm" },
            { label: "Style", value: "Divine Figures Collection" }
        ]
    },
    {
        name: "Statement Solitaire Pendant",
        slug: "diamond-solitaire-pendant",
        category: "pendants",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18],
        base_weight_grams: 8,
        making_charges_per_gram: 800,
        images: ["/images/Gemini_Generated_Image_nplamvnplamvnpla.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A dramatic 18K yellow gold solitaire pendant featuring a massive 2.50-carat equivalent round brilliant cut stone. Presented in a minimalist 4-prong basket setting to maximize light and brilliance.",
        short_description: "2.5ct statement solitaire in 18K gold",
        tags: ["diamond", "solitaire", "women", "luxury"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 15,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Main Stone", value: "2.50 carat Round Brilliant Cut (D VVS1)" },
            { label: "Setting", value: "4-prong minimalist basket" },
            { label: "Gold Weight", value: "8 grams (estimated)" },
            { label: "Style", value: "Solitaire Statement Collection" }
        ]
    },
    {
        name: "Blue Moonstone Heart Locket",
        slug: "heart-locket",
        category: "pendants",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18],
        base_weight_grams: 12,
        making_charges_per_gram: 600,
        images: ["/images/Gemini_Generated_Image_rfwauarfwauarfwa.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "An ethereal 18K white gold locket featuring a large pear-shaped blue moonstone as the central focus. Accented with graduating Ceylon sapphire raindrops, this piece captures the serenity of the moon.",
        short_description: "10ct Moonstone heart locket with sapphires",
        tags: ["romantic", "locket", "women", "gift"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 16,
        specifications: [
            { label: "Metal", value: "18K Solid White Gold" },
            { label: "Main Stone", value: "10.00 carat Pear-Shaped Moonstone" },
            { label: "Accents", value: "Ceylon Sapphire raindrops (0.70 ctw)" },
            { label: "Gold Weight", value: "12 grams (estimated)" },
            { label: "Style", value: "Blue Serenity Collection" }
        ]
    },
    {
        name: "Diamond Evil Eye Amulet",
        slug: "evil-eye-pendant",
        category: "pendants",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18],
        base_weight_grams: 9,
        making_charges_per_gram: 650,
        images: ["/images/Gemini_Generated_Image_rig8cbrig8cbrig8.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A sophisticated protective charm in 18K gold. This Evil Eye amulet is pavé-set with brilliant-cut diamonds and a central blue sapphire 'pupil', combining tradition with high-fashion couture.",
        short_description: "Diamond-encrusted 18K Evil Eye protection",
        tags: ["protective", "trending", "women", "diamond"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 17,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Diamonds", value: "0.85 total carat weight" },
            { label: "Center Stone", value: "0.30ct Ceylon Blue Sapphire" },
            { label: "Gold Weight", value: "9 grams (estimated)" },
            { label: "Style", value: "Modern Talisman Series" }
        ]
    },
    {
        name: "Pavé Diamond Heritage Cross",
        slug: "cross-pendant",
        category: "pendants",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18, 22],
        base_weight_grams: 13,
        making_charges_per_gram: 700,
        images: ["/images/Gemini_Generated_Image_mi94qrmi94qrmi94.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A stunning 18K yellow gold Latin Cross pendant, completely pavé-set with brilliant-cut diamonds. A symbol of faith reimagined through the lens of luxury jewelry craftsmanship.",
        short_description: "1.5ct diamond-set Latin cross (18K)",
        tags: ["religious", "men", "unisex", "diamond"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 18,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Diamonds", value: "1.50 total carat weight (F color, VS)" },
            { label: "Gold Weight", value: "13 grams (estimated)" },
            { label: "Dimensions", value: "45mm x 30mm" },
            { label: "Style", value: "Couture Faith Collection" }
        ]
    },

    // ─── BRACELETS ───
    {
        name: "Diamond Tennis Bracelet 7\"",
        slug: "tennis-bracelet",
        category: "bracelets",
        metal: "gold",
        default_karat: 18,
        available_karats: [18, 22],
        base_weight_grams: 12,
        making_charges_per_gram: 550,
        images: ["/images/Gemini_Generated_Image_dmbzk1dmbzk1dmbz.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A stunning 18K yellow gold single-row diamond tennis bracelet. Featuring 58 perfectly matched brilliant-cut diamonds in a secure box clasp assembly.",
        short_description: "4.5ct diamond tennis bracelet (18K)",
        tags: ["classic", "women", "luxury", "investment"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 19,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Diamonds", value: "4.50 total carat weight (58 Stones)" },
            { label: "Quality", value: "F-G color, VVS clarity" },
            { label: "Gold Weight", value: "12 grams (estimated)" },
            { label: "Length", value: "7 inches" },
            { label: "Clasp", value: "Box clasp with dual safety hinges" }
        ]
    },
    {
        name: "Artisanal Textured Gold Cuff",
        slug: "cuff-bracelet",
        category: "bracelets",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 25,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_tws7abtws7abtws7.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A bold, statement cuff in 22K solid gold. Featuring a hand-hammered texture that captures light from every angle, this architectural piece is for the modern connoisseur of fine gold.",
        short_description: "Hand-hammered 25g solid 22K gold cuff",
        tags: ["statement", "men", "women", "luxury"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 20,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "25 grams (estimated)" },
            { label: "Texture", value: "Artisan Repoussé / Hammered" },
            { label: "Inner Diameter", value: "65mm (Standard)" },
            { label: "Style", value: "Architectural Gold Series" }
        ]
    },
    {
        name: "Polished Interlocking Link Bracelet",
        slug: "link-bracelet",
        category: "bracelets",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18, 22],
        base_weight_grams: 14,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_mdofacmdofacmdof.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A highly flexible and comfortable everyday luxury. Polished interlocking links in 18K gold provide a substantial feel without compromising on elegance.",
        short_description: "Polished 18K gold interlocking links",
        tags: ["versatile", "men", "daily", "classic"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 21,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Gold Weight", value: "14 grams (estimated)" },
            { label: "Link Type", value: "Flat Curb Interlock" },
            { label: "Length", value: "7.5 inches" },
            { label: "Clasp", value: "Lobster Claw (Reinforced)" }
        ]
    },

    // ─── EARRINGS ───
    {
        name: "Divine Heritage Filigree Jhumkas",
        slug: "jhumka-earrings",
        category: "earrings",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 18,
        making_charges_per_gram: 750,
        images: ["/images/Gemini_Generated_Image_s8d9w8s8d9w8s8d9.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A masterpiece of Chennai craftsmanship. These 22K yellow gold jhumkas feature complex filigree work, dangling drops, and intricate umbrella-style tiers.",
        short_description: "Artisan 18g 22K gold heritage jhumkas",
        tags: ["traditional", "bridal", "women", "heritage"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 23,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "18 grams (estimated)" },
            { label: "Findings", value: "Secure Bombay Screw" },
            { label: "Style", value: "Temple Series Heritage" },
            { label: "Hallmark", value: "BIS 916 (Chennai)" }
        ]
    },
    {
        name: "Textured Gold Hoop Earrings",
        slug: "hoop-earrings-30mm",
        category: "earrings",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18, 22],
        base_weight_grams: 5,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_8jl7m08jl7m08jl7.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Elevated essentials. These 30mm hoops feature a subtle micro-textured finish that catches the light differently than standard high-polish alternatives.",
        short_description: "30mm textured 18K gold hoops",
        tags: ["daily", "women", "essential", "style"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 24,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Gold Weight", value: "5 grams (estimated)" },
            { label: "Diameter", value: "30mm" },
            { label: "Thickness", value: "2mm Tube" },
            { label: "Clasp", value: "Catch & Snap (Seamless)" }
        ]
    },
    {
        name: "Minimalist Domed Gold Studs",
        slug: "stud-earrings",
        category: "earrings",
        metal: "gold",
        default_karat: 22,
        available_karats: [14, 18, 22],
        base_weight_grams: 3,
        making_charges_per_gram: 600,
        images: ["/images/Gemini_Generated_Image_yxrfo4yxrfo4yxrf.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Pure radiance in a compact form. These 22K solid gold studs feature a high-polish domed profile designed for maximum brilliance and daily comfort.",
        short_description: "Pure 22K gold 8mm domed studs",
        tags: ["minimalist", "women", "office", "everyday"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 25,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "3 grams (estimated)" },
            { label: "Diameter", value: "8mm" },
            { label: "Findings", value: "Threaded Screw-back" },
            { label: "Hallmark", value: "BIS 916" }
        ]
    },
    {
        name: "Gold Tassel Drop Earrings",
        slug: "drop-earrings",
        category: "earrings",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 6,
        making_charges_per_gram: 700,
        images: ["/images/Gemini_Generated_Image_u43qp4u43qp4u43q.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Graceful movement captured in gold. These drop earrings feature articulated tassels that sway elegance with every turn of the head.",
        short_description: "Elegant 22K gold articulated tassels",
        tags: ["elegant", "women", "party", "fluid"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 26,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "6 grams (estimated)" },
            { label: "Drop Length", value: "40mm" },
            { label: "Findings", value: "Hook with safety catch" },
            { label: "Style", value: "Evening Grace Collection" }
        ]
    },
    {
        name: "Royal Moon Filigree Chandbalis",
        slug: "chandbali-earrings",
        category: "earrings",
        metal: "gold",
        default_karat: 22,
        available_karats: [22],
        base_weight_grams: 14,
        making_charges_per_gram: 800,
        images: ["/images/Gemini_Generated_Image_udo0xnudo0xnudo0.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Exquisite 22K gold crescent moon (Chand) earrings. Featuring hand-woven gold wire filigree and suspended with rare, high-luster freshwater pearls.",
        short_description: "22K gold crescent filigree with pearls",
        tags: ["traditional", "bridal", "luxury", "regal"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 27,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Stones", value: "Freshwater Seed Pearls" },
            { label: "Gold Weight", value: "14 grams (estimated)" },
            { label: "Inner Diameter", value: "35mm Crescent" },
            { label: "Style", value: "Nizam Heritage Collection" }
        ]
    },
    {
        name: "Articulated Pavé Ear Cuff Set",
        slug: "ear-cuff",
        category: "earrings",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18],
        base_weight_grams: 5,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_i0fn5di0fn5di0fn.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Modern couture for the ear. This 18K white gold ear cuff is fully articulated to fit the cartilage perfectly and is pavé-set with brilliant diamonds.",
        short_description: "Diamond pavé 18K white gold ear cuff",
        tags: ["trending", "women", "modern", "edge"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 28,
        specifications: [
            { label: "Metal", value: "18K Solid White Gold" },
            { label: "Diamonds", value: "0.50 total carat weight (G-H, VS)" },
            { label: "Gold Weight", value: "5 grams (estimated)" },
            { label: "Mechanism", value: "Pressure-fit hinged articulation" },
            { label: "Style", value: "Parisian Modern Series" }
        ]
    },

    // ─── BANGLES ───
    {
        name: "Classic Solid Gold Bangle",
        slug: "plain-bangle",
        category: "bangles",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 12,
        making_charges_per_gram: 400,
        images: ["/images/Gemini_Generated_Image_vdxpe6vdxpe6vdxp.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "The quintessential gold bangle. Forged from solid 22K gold with a substantial rounded profile and a mirror-polish finish.",
        short_description: "Classic rounded 22K gold bangle",
        tags: ["daily", "women", "classic", "investment"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 29,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "12 grams (estimated)" },
            { label: "Shape", value: "Full-round Solid Profile" },
            { label: "Sizes", value: "2.4, 2.6, 2.8 available" },
            { label: "Hallmark", value: "BIS 916" }
        ]
    },
    {
        name: "Heritage Hand-Carved Kada",
        slug: "kada-bangle",
        category: "bangles",
        metal: "gold",
        default_karat: 22,
        available_karats: [22],
        base_weight_grams: 18,
        making_charges_per_gram: 500,
        images: ["/images/Gemini_Generated_Image_hm8xhrhm8xhrhm8x.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A heavyweight symbol of strength. This 22K gold kada features hand-carved terminal details inspired by ancient architecture.",
        short_description: "Heavyweight 18g 22K gold carved kada",
        tags: ["men", "traditional", "heavy", "status"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 30,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "18 grams (estimated)" },
            { label: "Thickness", value: "8mm central shaft" },
            { label: "Design", value: "Ancient Terminal Relief" },
            { label: "Finish", value: "Satin and High-Polish contrast" }
        ]
    },
    {
        name: "Adjustable First-Gift Baby Bangle",
        slug: "baby-bangle",
        category: "bangles",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 4,
        making_charges_per_gram: 600,
        images: ["/images/Gemini_Generated_Image_skdeniskdeniskde.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A precious investment for the little ones. Smoothly finished 22K gold with a sliding adjustment system for a perfect fit as they grow.",
        short_description: "Smooth adjustable 22K baby bangle",
        tags: ["baby", "gift", "ceremony", "keepsake"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 31,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "4 grams (estimated)" },
            { label: "Sizing", value: "1.2 to 1.6 (Adjustable)" },
            { label: "Edge", value: "Deburred Silk-Smooth" }
        ]
    },

    // ─── NECKLACES ───
    {
        name: "Divine Lakshmi Kasu Mala",
        slug: "temple-necklace",
        category: "necklaces",
        metal: "gold",
        default_karat: 22,
        available_karats: [22],
        base_weight_grams: 125,
        making_charges_per_gram: 800,
        images: ["/images/Gemini_Generated_Image_wv3kvpwv3kvpwv3k.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A magnificent handcrafted 22K yellow gold Temple-style kasu-mala. Featuring intricately engraved interlocking coins and a large central pendant of Goddess Lakshmi.",
        short_description: "Imperial 125g 22K Temple necklace",
        tags: ["bridal", "women", "luxury", "temple"],
        is_active: true,
        is_featured: true,
        is_ai_generated: false,
        sort_order: 32,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "125 grams (estimated)" },
            { label: "Stones", value: "Kundan-set Rubies and Emeralds" },
            { label: "Length", value: "18 inches (adjustable dori)" },
            { label: "Pendant Size", value: "50mm Diameter" },
            { label: "Hallmark", value: "BIS 916 (Chennai)" }
        ]
    },
    {
        name: "Diamond Rose Bridal Choker Set",
        slug: "choker-set",
        category: "necklaces",
        metal: "gold",
        default_karat: 18,
        available_karats: [18, 22],
        base_weight_grams: 45,
        making_charges_per_gram: 750,
        images: ["/images/Gemini_Generated_Image_g1bsclg1bsclg1bs.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "An extraordinary 18K white gold choker set featuring a central rose motif. Encrusted with over 15 carats of brilliant-cut diamonds, this set includes matching drop earrings for the ultimate bridal statement.",
        short_description: "15ct diamond rose choker & earring set",
        tags: ["bridal", "women", "set", "wedding"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 33,
        specifications: [
            { label: "Metal", value: "18K Solid White Gold" },
            { label: "Diamonds", value: "15.00+ total carat weight (F-G, VVS)" },
            { label: "Gold Weight", value: "45 grams (excluding stones)" },
            { label: "Set Includes", value: "Choker and matching Drop Earrings" },
            { label: "Style", value: "Imperial Bridal Collection" }
        ]
    },
    {
        name: "Triple-Layer Heritage Wheat Necklace",
        slug: "layered-necklace",
        category: "necklaces",
        metal: "gold",
        default_karat: 18,
        available_karats: [14, 18],
        base_weight_grams: 48,
        making_charges_per_gram: 600,
        images: ["/images/Gemini_Generated_Image_mmrhhommrhhommrh.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "Three varying lengths of hand-woven 18K gold Wheat chains, pre-layered to perfection. Each chain features a slightly different gauge for a complex, rich golden drape.",
        short_description: "Pre-layered 48g 18K triple wheat chain",
        tags: ["trending", "women", "modern", "chic"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 34,
        specifications: [
            { label: "Metal", value: "18K Solid Yellow Gold" },
            { label: "Gold Weight", value: "48 grams (estimated)" },
            { label: "Layer Lengths", value: "16\", 18\", and 20\"" },
            { label: "Chain Type", value: "Espiga (Wheat) Triple Weave" },
            { label: "Clasp", value: "Oversized Decorative Toggle" }
        ]
    },
    {
        name: "Minimalist Sacred Mangalsutra",
        slug: "mangalsutra",
        category: "necklaces",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 8,
        making_charges_per_gram: 700,
        images: ["/images/Gemini_Generated_Image_mgs79ymgs79ymgs7.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A modern interpretation of the sacred union. This 22K gold mangalsutra features a sleek, minimalist bar pendant and faceted black beads for a contemporary everyday look.",
        short_description: "Modern minimalist 22K gold mangalsutra",
        tags: ["bridal", "women", "daily", "traditional"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 35,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "8 grams (estimated)" },
            { label: "Stones", value: "Faceted Black Onyx beads" },
            { label: "Chain Type", value: "Strong flat-link gold chain" },
            { label: "Length", value: "16 inches" }
        ]
    },
    {
        name: "Imperial Coin Prosperity Necklace",
        slug: "coin-necklace",
        category: "necklaces",
        metal: "gold",
        default_karat: 22,
        available_karats: [18, 22],
        base_weight_grams: 35,
        making_charges_per_gram: 550,
        images: ["/images/Gemini_Generated_Image_ksbnm9ksbnm9ksbn.png"],
        thumbnail_url: null,
        model_3d_url: null,
        description: "A series of 22K gold Kasu (coins) meticulously linked on a heavy anchor chain. Each coin is stamped with symbols of wealth and prosperity, representing a timeless heritage legacy.",
        short_description: "35g 22K gold Kasu prosperity necklace",
        tags: ["trending", "heritage", "unisex", "value"],
        is_active: true,
        is_featured: false,
        is_ai_generated: false,
        sort_order: 36,
        specifications: [
            { label: "Metal", value: "22K Solid Yellow Gold" },
            { label: "Gold Weight", value: "35 grams (estimated)" },
            { label: "Number of Coins", value: "21 (Individually Stamped)" },
            { label: "Chain Type", value: "Imperial Anchor Link" },
            { label: "Hallmark", value: "BIS 916" }
        ]
    },
];
