// 36 product seed data for AUREUM catalog
import type { Product } from './types'

export const SEED_PRODUCTS: Omit<Product, 'id' | 'created_at' | 'views'>[] = [
    // ─── RINGS ───
    { name: "Classic 22K Band", slug: "classic-22k-band", category: "rings", metal: "gold", default_karat: 22, available_karats: [14, 18, 22], base_weight_grams: 6, making_charges_per_gram: 450, images: [], thumbnail_url: null, model_3d_url: null, description: "A timeless solid gold band crafted in premium 22K gold, perfect for daily wear. Smooth matte finish with a comfortable flat interior.", short_description: "Timeless solid gold band, daily wear", tags: ["classic", "daily", "men", "women"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 1 },
    { name: "Signet Ring", slug: "signet-ring", category: "rings", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 8, making_charges_per_gram: 550, images: [], thumbnail_url: null, model_3d_url: null, description: "Bold signet ring with a flat top perfect for engraving initials or family crests. A statement piece that combines heritage with modern style.", short_description: "Bold signet with flat top, engravable", tags: ["statement", "men", "engravable"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 2 },
    { name: "Minimalist 18K Ring", slug: "minimalist-18k-ring", category: "rings", metal: "gold", default_karat: 18, available_karats: [14, 18], base_weight_grams: 4, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "A thin, elegant modern band in 18K gold. Office-friendly and understated, perfect for those who prefer subtlety.", short_description: "Thin modern band, office-friendly", tags: ["minimalist", "office", "women"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 3 },
    { name: "Stacking Rings Set ×3", slug: "stacking-rings-set", category: "rings", metal: "gold", default_karat: 14, available_karats: [14, 18], base_weight_grams: 6, making_charges_per_gram: 400, images: [], thumbnail_url: null, model_3d_url: null, description: "Three delicate stackable rings that can be worn individually or together. Mix and match for your personal style.", short_description: "Three delicate stackable rings", tags: ["trending", "women", "gift"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 4 },
    { name: "Twisted Rope Ring", slug: "twisted-rope-ring", category: "rings", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 5, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Hand-twisted rope texture ring crafted by master goldsmiths. Each ring is unique with its own character.", short_description: "Hand-twisted rope texture", tags: ["artisan", "textured", "women"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 5 },
    { name: "Dome Cocktail Ring", slug: "dome-cocktail-ring", category: "rings", metal: "gold", default_karat: 18, available_karats: [18, 22], base_weight_grams: 10, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "A bold statement dome ring that catches light from every angle. Perfect for parties and celebrations.", short_description: "Statement dome ring for parties", tags: ["statement", "party", "women"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 6 },

    // ─── CHAINS ───
    { name: "Cuban Link 20\"", slug: "cuban-link-20", category: "chains", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 18, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Classic Cuban link chain in premium 22K gold. 20 inches of pure luxury with a secure lobster clasp.", short_description: "Classic Cuban link, 20 inches", tags: ["classic", "men", "statement"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 7 },
    { name: "Cuban Link 24\"", slug: "cuban-link-24", category: "chains", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 24, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Statement Cuban link chain at 24 inches. Thick, heavy, and commanding. The ultimate gold chain.", short_description: "Statement Cuban link, 24 inches", tags: ["statement", "men", "heavy"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 8 },
    { name: "Box Chain 18\"", slug: "box-chain-18", category: "chains", metal: "gold", default_karat: 22, available_karats: [14, 18, 22], base_weight_grams: 10, making_charges_per_gram: 450, images: [], thumbnail_url: null, model_3d_url: null, description: "Sleek box chain with square links that catch light beautifully. Versatile enough for pendants or solo wear.", short_description: "Sleek box chain, versatile", tags: ["versatile", "men", "women", "pendant-ready"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 9 },
    { name: "Rope Chain 22\"", slug: "rope-chain-22", category: "chains", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 15, making_charges_per_gram: 550, images: [], thumbnail_url: null, model_3d_url: null, description: "Twisted rope chain with a luxurious shimmer. 22 inches of hand-crafted gold rope.", short_description: "Twisted rope, medium weight", tags: ["classic", "men", "textured"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 10 },
    { name: "Figaro Chain 20\"", slug: "figaro-chain-20", category: "chains", metal: "gold", default_karat: 18, available_karats: [14, 18, 22], base_weight_grams: 12, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Italian Figaro pattern with alternating link sizes. A Mediterranean classic in gold.", short_description: "Italian Figaro pattern", tags: ["italian", "men", "classic"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 11 },
    { name: "Wheat Chain 18\"", slug: "wheat-chain-18", category: "chains", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 8, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Delicate wheat weave chain that drapes beautifully. Lightweight yet strong with intricate craftsmanship.", short_description: "Delicate wheat weave", tags: ["delicate", "women", "artisan"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 12 },

    // ─── PENDANTS ───
    { name: "Om Pendant", slug: "om-pendant", category: "pendants", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 4, making_charges_per_gram: 700, images: [], thumbnail_url: null, model_3d_url: null, description: "Sacred Om symbol intricately carved in 22K gold. A spiritual masterpiece for devotion and daily blessings.", short_description: "Sacred Om symbol, detailed", tags: ["spiritual", "men", "women", "gift"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 13 },
    { name: "Ganesh Pendant", slug: "ganesh-pendant", category: "pendants", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 6, making_charges_per_gram: 800, images: [], thumbnail_url: null, model_3d_url: null, description: "Lord Ganesh pendant with extraordinary detail. Removable obstacles, invoke prosperity with every wear.", short_description: "Lord Ganesh, prosperity blessing", tags: ["spiritual", "festival", "men", "women"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 14 },
    { name: "Diamond Solitaire Pendant", slug: "diamond-solitaire-pendant", category: "pendants", metal: "gold", default_karat: 18, available_karats: [14, 18], base_weight_grams: 3, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Single stone elegance in a minimal prong setting. The floating diamond effect creates timeless beauty.", short_description: "Single stone elegance", tags: ["diamond", "women", "office", "gift"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 15 },
    { name: "Heart Locket", slug: "heart-locket", category: "pendants", metal: "gold", default_karat: 18, available_karats: [14, 18], base_weight_grams: 5, making_charges_per_gram: 650, images: [], thumbnail_url: null, model_3d_url: null, description: "Openable heart-shaped locket for holding photos of loved ones. A personal treasure in gold.", short_description: "Openable heart locket", tags: ["sentimental", "women", "gift"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 16 },
    { name: "Evil Eye Pendant", slug: "evil-eye-pendant", category: "pendants", metal: "gold", default_karat: 18, available_karats: [14, 18], base_weight_grams: 3, making_charges_per_gram: 550, images: [], thumbnail_url: null, model_3d_url: null, description: "Protection charm with blue enamel evil eye set in 18K gold. Ward off negativity with style.", short_description: "Protection charm, blue enamel", tags: ["trending", "women", "protection"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 17 },
    { name: "Cross Pendant", slug: "cross-pendant", category: "pendants", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 5, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Simple cross design in polished gold. A timeless symbol of faith, beautifully crafted.", short_description: "Simple cross design", tags: ["spiritual", "men", "women", "daily"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 18 },

    // ─── BRACELETS ───
    { name: "Tennis Bracelet 7\"", slug: "tennis-bracelet", category: "bracelets", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 20, making_charges_per_gram: 550, images: [], thumbnail_url: null, model_3d_url: null, description: "Classic tennis-style bracelet in 22K gold. Uniform links that wrap the wrist in luxury.", short_description: "Classic tennis style, 7 inches", tags: ["classic", "women", "luxury"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 19 },
    { name: "Cuff Bracelet", slug: "cuff-bracelet", category: "bracelets", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 25, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Bold open cuff bracelet with a polished finish. Adjustable to any wrist size, a statement piece.", short_description: "Bold open cuff, adjustable", tags: ["statement", "men", "women", "adjustable"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 20 },
    { name: "Link Bracelet", slug: "link-bracelet", category: "bracelets", metal: "gold", default_karat: 18, available_karats: [14, 18, 22], base_weight_grams: 14, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Polished link chain bracelet in 18K gold. Versatile and comfortable for everyday wear.", short_description: "Polished link chain bracelet", tags: ["versatile", "men", "daily"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 21 },
    { name: "Charm Bracelet", slug: "charm-bracelet", category: "bracelets", metal: "gold", default_karat: 18, available_karats: [14, 18], base_weight_grams: 12, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Charm bracelet with secure links. Add your own charms to tell your personal story in gold.", short_description: "Add your own charms", tags: ["customizable", "women", "gift"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 22 },

    // ─── EARRINGS ───
    { name: "Jhumka Earrings", slug: "jhumka-earrings", category: "earrings", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 8, making_charges_per_gram: 750, images: [], thumbnail_url: null, model_3d_url: null, description: "Traditional bell-shaped jhumkas with intricate filigree work. A bridal essential and festival favorite.", short_description: "Traditional bell-shaped jhumkas", tags: ["traditional", "bridal", "women", "festival"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 23 },
    { name: "Hoop Earrings 30mm", slug: "hoop-earrings-30mm", category: "earrings", metal: "gold", default_karat: 18, available_karats: [14, 18, 22], base_weight_grams: 5, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Medium-sized hoop earrings perfect for daily wear. Smooth, lightweight, and endlessly versatile.", short_description: "Medium hoops, daily wear", tags: ["daily", "women", "versatile"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 24 },
    { name: "Stud Earrings", slug: "stud-earrings", category: "earrings", metal: "gold", default_karat: 22, available_karats: [14, 18, 22], base_weight_grams: 3, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Simple, elegant gold studs with a secure push-back closure. The everyday essential.", short_description: "Simple gold studs", tags: ["daily", "women", "minimalist", "office"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 25 },
    { name: "Drop Earrings", slug: "drop-earrings", category: "earrings", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 6, making_charges_per_gram: 700, images: [], thumbnail_url: null, model_3d_url: null, description: "Elegant tear-drop earrings that sway with movement. Perfect for evening events and celebrations.", short_description: "Elegant tear-drop design", tags: ["elegant", "women", "party", "evening"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 26 },
    { name: "Chandbali Earrings", slug: "chandbali-earrings", category: "earrings", metal: "gold", default_karat: 22, available_karats: [22], base_weight_grams: 10, making_charges_per_gram: 800, images: [], thumbnail_url: null, model_3d_url: null, description: "Moon-shaped traditional chandbalis with pearl drops. A royal Rajasthani design.", short_description: "Moon-shaped traditional chandbalis", tags: ["traditional", "bridal", "women", "luxury"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 27 },
    { name: "Ear Cuff", slug: "ear-cuff", category: "earrings", metal: "gold", default_karat: 14, available_karats: [14, 18], base_weight_grams: 2, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Trendy no-piercing ear cuff that clips on securely. Edge meets elegance.", short_description: "Trendy no-piercing ear cuff", tags: ["trending", "women", "no-piercing"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 28 },

    // ─── BANGLES ───
    { name: "Plain Bangle 2.4\"", slug: "plain-bangle", category: "bangles", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 12, making_charges_per_gram: 400, images: [], thumbnail_url: null, model_3d_url: null, description: "Smooth, polished daily wear bangle. Classic 2.4 inch diameter. Stack multiples for impact.", short_description: "Smooth daily wear bangle", tags: ["daily", "women", "classic", "stackable"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 29 },
    { name: "Kada Bangle", slug: "kada-bangle", category: "bangles", metal: "gold", default_karat: 22, available_karats: [22], base_weight_grams: 18, making_charges_per_gram: 500, images: [], thumbnail_url: null, model_3d_url: null, description: "Thick men's kada bangle with an open design. A traditional Sikh/Punjabi essential in pure gold.", short_description: "Thick men's kada", tags: ["men", "traditional", "heavy", "punjabi"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 30 },
    { name: "Baby Bangle", slug: "baby-bangle", category: "bangles", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 4, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Adorable adjustable bangle for little ones. Safe edges, lightweight, perfect for naming ceremonies.", short_description: "For little ones, adjustable", tags: ["baby", "gift", "ceremony"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 31 },

    // ─── NECKLACES ───
    { name: "Temple Necklace", slug: "temple-necklace", category: "necklaces", metal: "gold", default_karat: 22, available_karats: [22], base_weight_grams: 30, making_charges_per_gram: 800, images: [], thumbnail_url: null, model_3d_url: null, description: "Grand temple jewelry necklace with intricate deity motifs. The quintessential South Indian bridal piece.", short_description: "Grand temple jewelry, bridal", tags: ["bridal", "women", "luxury", "temple", "south-indian"], is_active: true, is_featured: true, is_ai_generated: false, sort_order: 32 },
    { name: "Choker Set", slug: "choker-set", category: "necklaces", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 20, making_charges_per_gram: 750, images: [], thumbnail_url: null, model_3d_url: null, description: "Close-fit choker necklace with matching earrings. A complete bridal set in 22K gold.", short_description: "Close-fit choker with earrings", tags: ["bridal", "women", "set", "wedding"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 33 },
    { name: "Layered Necklace", slug: "layered-necklace", category: "necklaces", metal: "gold", default_karat: 18, available_karats: [14, 18], base_weight_grams: 10, making_charges_per_gram: 600, images: [], thumbnail_url: null, model_3d_url: null, description: "Three-layer modern necklace with varying chain lengths. The trendy way to wear gold.", short_description: "3-layer modern necklace", tags: ["trending", "women", "modern", "layered"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 34 },
    { name: "Mangalsutra", slug: "mangalsutra", category: "necklaces", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 8, making_charges_per_gram: 700, images: [], thumbnail_url: null, model_3d_url: null, description: "Modern mangalsutra design blending tradition with contemporary aesthetics. Daily wear comfort.", short_description: "Modern mangalsutra design", tags: ["bridal", "women", "daily", "traditional"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 35 },
    { name: "Coin Necklace", slug: "coin-necklace", category: "necklaces", metal: "gold", default_karat: 22, available_karats: [18, 22], base_weight_grams: 12, making_charges_per_gram: 550, images: [], thumbnail_url: null, model_3d_url: null, description: "Gold coin pendant on a fine chain. Ancient Roman-inspired design meets modern craftsmanship.", short_description: "Gold coin pendant necklace", tags: ["trending", "men", "women", "coin"], is_active: true, is_featured: false, is_ai_generated: false, sort_order: 36 },
]
